name: riverpod_todo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hive: ^2.2.3
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: P
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

